#!/bin/bash
#install R
 sudo yum install R
#install RStudio-Server 
wget https://download2.rstudio.org/rstudio-server-rhel-0.99.489-x86_64.rpm
$ sudo yum install --nogpgcheck rstudio-server-rhel-0.99.489-x86_64.rpm
#install shiny and shiny-server
R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"
wget https://download3.rstudio.org/centos5.9/x86_64/shiny-server-1.4.0.718-rh5-x86_64.rpm
yum install -y --nogpgcheck shiny-server-1.4.0.718-rh5-x86_64.rpm
#add user(s)
useradd username
echo username:password | chpasswd

#enable install packages 
sudo yum install curl-devel
